storage_path: "/mnt/towbin.data/shared"
valid_subdirectories: ["plenart", "kstojanovski"]

database_path: "/mnt/towbin.data/shared/spsalmon/towbinlab_classification_database/datasets/10x_body_qc"

database_configs: {
  'body': {
      'size': 2000,
      # 'stage_proportions': {'L1': 0.25, 'L2': 0.25, 'L3': 0.25, 'L4': 0.25,},
      'scope_proportions': {'ti2': 0.5, 'squid': 0.5},
      'channel': [1],
      'strains': ["186", "160", "125", "318", "446"],
      'magnification': "10x",
  },
}

# smoother configuration
lambda: 0.0075
# threshold quantile
threshold: 0.90

# sets a limit on how far after M4 images will be included
extra_adulthood_time: 40
n_picks_per_stage: 50

valid_scopes: ["squid", "ti2"]
scopes_alt_names: {
  'crest': ['Crest', 'crest', 'CREST'],
  'squid': ['Squid', 'squid', 'SQUID'],
  'ti2': ['Ti2', 'ti2', 'TI2', 'orca', 'Orca', 'ORCA'],
  'ziva': ['ziva', 'ZIVA', 'Ziva']
}

keywords_to_exclude: ["exclude", "fail", "failure", "crash"]
keywords_to_include: []

experiments_to_consider: []

experient_to_always_include: []
experiments_to_exclude: [
  "20241111_squid_10x_wBT318_NaCl",
  "20241707_souvik_w318_ev_mex3_squid",
  "20240515_squid1_10x_wbt160_25C_2024-05-15_15-31-45.506118",
  "20240212_squid_wbt318_Nacl",
  "20241912_squid_10x_wBT_344_415",
  "20252401_squid_10x_wBT318_reproduction",
  "20252001_squid_10x_wBT318_NaCl",
]
