storage_path: "/mnt/towbin.data/shared"
valid_subdirectories: ["plenart"]

database_path: "/mnt/towbin.data/shared/spsalmon/towbinlab_segmentation_database/lifespan"

database_configs: {
  'body': {
      'size': 1000,
      'stage_proportions': {'adult': 0.5, 'larvae': 0.5},
      'scope_proportions': {'squid': 1.0},
      'channel': [1],
      'strains': [],
      'magnification': "10x",
  },
  'germline': {
      'size': 1000,
      'stage_proportions': {'adult': 0.5, 'larvae': 0.5},
      'scope_proportions': {'squid': 1.0},
      'channel': [0],
      'strains': [],
      'magnification': "10x",
  },
}

# sets a limit on how far after M4 images will be included
extra_adulthood_time: 40

valid_scopes: ["squid"]
scopes_alt_names: {
  'crest': ['Crest', 'crest', 'CREST'],
  'squid': ['Squid', 'squid', 'SQUID'],
  'ti2': ['Ti2', 'ti2', 'TI2', 'orca', 'Orca', 'ORCA']
}

keywords_to_exclude: ["exclude", "fail", "failure", "crash"]
keywords_to_include: ["lifespan"]

experiments_to_consider: [
  '/mnt/towbin.data/shared/plenart/20251508_lifespan_squid_10x_wBT318_wBT486_25Â°C_small',
  '/mnt/towbin.data/shared/plenart/20250407_lifespan_squid_10x_wBT546_wBT547_auxin_20_degrees',
]

experient_to_always_include: []
experiments_to_exclude: [
  "20241111_squid_10x_wBT318_NaCl",
  "20241707_souvik_w318_ev_mex3_squid",
  "20240515_squid1_10x_wbt160_25C_2024-05-15_15-31-45.506118",
  "20240212_squid_wbt318_Nacl",
  "20241912_squid_10x_wBT_344_415",
  "20252401_squid_10x_wBT318_reproduction",
  "20252001_squid_10x_wBT318_NaCl",
]
